### ISSUE TITLE
NPE when a user does not have any roles

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard-module-kibana-multitenancy#10]
This may be a corner case, but we should fix it nonetheless:

1. Enable multi-tenancy in your ES cluster
2. Log in with a user that does not have any roles
2.1 In this case, the user credentials stem from a JWT token, but I guess it's irrelevant where it comes from

Result: NPE in PrivilegesEvaluator:

```
[2017-06-27T15:20:58,520][DEBUG][c.f.s.a.BackendRegistry  ] User 'xxx' is in cache? true (cache size: 3)
[2017-06-27T15:20:58,520][DEBUG][c.f.s.a.BackendRegistry  ] User 'User [name=xxx, roles=[]]' is authenticated
[2017-06-27T15:20:58,520][DEBUG][c.f.s.a.BackendRegistry  ] sg_tenant 'null'
[2017-06-27T15:20:58,521][DEBUG][c.f.s.c.PrivilegesEvaluator] evaluate permissions for User [name=xxx, roles=[]]
[2017-06-27T15:20:58,521][DEBUG][c.f.s.c.PrivilegesEvaluator] requested indices:data/read/get from 10.2.9.18:57394
[2017-06-27T15:20:58,521][DEBUG][c.f.s.c.PrivilegesEvaluator] Resolve [.kibana] from class org.elasticsearch.action.get.GetRequest
[2017-06-27T15:20:58,522][DEBUG][c.f.s.c.PrivilegesEvaluator] indicesOptions IndicesOptions[id=48, ignore_unavailable=false, allow_no_indices=false, expand_wildcards_open=false, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=false, forbid_closed_indices=true]
[2017-06-27T15:20:58,522][DEBUG][c.f.s.c.PrivilegesEvaluator] raw indices [.kibana]
[2017-06-27T15:20:58,522][DEBUG][c.f.s.c.PrivilegesEvaluator] Resolved [.kibana] to [.kibana]
[2017-06-27T15:20:58,522][DEBUG][c.f.s.c.PrivilegesEvaluator] requested resolved indextypes: [IndexType [index=.kibana, type=config]]
[2017-06-27T15:20:58,522][DEBUG][c.f.s.c.PrivilegesEvaluator] mapped roles for xxx: []
[2017-06-27T15:20:58,522][DEBUG][c.f.s.c.PrivilegesInterceptorImpl] raw requestedTenant: 'null'
[2017-06-27T15:20:58,522][INFO ][c.f.s.c.PrivilegesEvaluator] No index-level perm match for User [name=xxx, roles=[]] [IndexType [index=.kibana, type=config]] [Action [indices:data/read/get]] [RolesChecked []]
[2017-06-27T15:20:58,522][INFO ][c.f.s.c.PrivilegesEvaluator] No permissions for {}
[2017-06-27T15:20:58,522][WARN ][r.suppressed             ] path: /.kibana/config/5.4.0, params: {index=.kibana, id=5.4.0, type=config}
java.lang.NullPointerException: null
at com.floragunn.searchguard.configuration.PrivilegesInterceptorImpl.replaceAllowedIndices(PrivilegesInterceptorImpl.java:543) ~[?:?]
at com.floragunn.searchguard.configuration.PrivilegesEvaluator.evaluate(PrivilegesEvaluator.java:692) ~[?:?]
at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:145) ~[?:?]
at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:168) ~[elasticsearch-5.4.1.jar:5.4.1]
at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:142) ~[elasticsearch-5.4.1.jar:5.4.1]
at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:84) ~[elasticsearch-5.4.1.jar:5.4.1]
at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[elasticsearch-5.4.1.jar:5.4.1]
at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) ~[elasticsearch-5.4.1.jar:5.4.1]
at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408) ~[elasticsearch-5.4.1.jar:5.4.1]
at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:500) ~[elasticsearch-5.4.1.jar:5.4.1]
...
```

**Comment by floragunn** [comment]
fixed with v3 of the multi tenancy module (or use SG 14 which contains a fix that will work with v2 of this module)
